### ISSUE TITLE
Log may not be available after redeploy

### ISSUE THREAD

**Issue by pascalfree** [juntagrico/juntagrico-paas#4]
This happens, when waiting for a while (around 15 minutes) after the redeploy and then clicking next

```
Traceback (most recent call last):
  File "/var/django/adminconsole/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/var/django/adminconsole/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/django/adminconsole/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/django/adminconsole/adminconsole/decorators.py", line 16, in wrapper
    return view(request, *args, **kwargs)
  File "/var/django/adminconsole/adminconsole/views.py", line 62, in show_log
    texts = [str(eval(b_text), 'utf-8') if b_text.startswith('b') else b_text for b_text in b_texts]
  File "/var/django/adminconsole/adminconsole/views.py", line 62, in <listcomp>
    texts = [str(eval(b_text), 'utf-8') if b_text.startswith('b') else b_text for b_text in b_texts]

Exception Type: SyntaxError at /showlog/33/
Exception Value: invalid syntax (<string>, line 1)
```

**Comment by motu55** [comment]
i do not think it is a timing issue but the log may have a form which cannot be parsed by the list comprehension
to check and reproduce we would need the log at that time from the server

**Comment by pascalfree** [comment]
Got the error again. The file contains 
```
b"[...] 'pip install --upgrade pip' command.\n"Traceback (most recent call last):
```
I guess the issue is that the text after " is in the same line.

The original error causing this seems to be due to a timeout.
